FROM node:22-alpine

WORKDIR /app

# Install dependencies
RUN apk add --no-cache git

# Expose Vite dev server port
EXPOSE 5175

# Install deps and start dev server
CMD ["sh", "-c", "npm install && npm run dev -- --host 0.0.0.0 --port 5175"]
